# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 556aa24d71e3dbe84eb6f5a7ca80baaaedfeaaabe162e82ea778f365de6c49d74a5f8596a921e33e6176a12162d9a0572bc292ec4e9115b77384225665465416

test:
  secret_key_base: a23bc90af6f41d7d4cb67f3c35e39bd82dd4457c2c6718fd7df68368d957b3bd33bbd2311b229243472ca072f031734fb3bccf4026d90cce8587f8855b8e0ac8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
